name: tdd_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'
#  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.1.0
  bloc: ^8.1.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mocktail: ^1.0.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
